# Generated by Django 3.1 on 2021-07-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_valur',
            new_name='variation_value',
        ),
    ]
