# Generated by Django 3.1 on 2021-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210703_1115'),
        ('cart', '0003_auto_20210725_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='store.Variation'),
        ),
    ]
